version: '3.8'

services:
  frontend_ug:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8080}
        VITE_PUSHER_APP_KEY: ${VITE_PUSHER_APP_KEY:-ae75f3a73201ef37c668}
        VITE_PUSHER_APP_CLUSTER: ${VITE_PUSHER_APP_CLUSTER:-eu}
        VITE_PUSHER_BASE_URL: ${VITE_PUSHER_BASE_URL:-http://localhost:8080}
    image: gfa_frontend_ug:local
    container_name: gfa_frontend_ug_local
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local

networks:
  default:
    name: gfa_se_backend_webapp_gfa-network
    external: true
