version: '3.8'

services:
  frontend_ug:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://dms-redevabilite.dev}
        VITE_PUSHER_APP_KEY: ${VITE_PUSHER_APP_KEY:-ae75f3a73201ef37c668}
        VITE_PUSHER_APP_CLUSTER: ${VITE_PUSHER_APP_CLUSTER:-eu}
        VITE_PUSHER_BASE_URL: ${VITE_PUSHER_BASE_URL:-https://dms-redevabilite.dev}
    image: gfa_frontend_ug:staging
    container_name: gfa_frontend_ug_staging
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=staging
    env_file:
      - .env.staging

networks:
  default:
    name: gfa_se_backend_webapp_gfa-network
    external: true
